// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaintApp_Data.Context;

#nullable disable

namespace PaintApp_Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206154504_SeedAdminData")]
    partial class SeedAdminData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("PaintApp_Data.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarIcon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCanvasColor")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultCanvasHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultCanvasWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("DefaultStrokeColor")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultStrokeSize")
                        .HasColumnType("REAL");

                    b.Property<int>("DefaultStrokeStyle")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemePreference")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarIcon = "Assets/DefaultAvatar.jpg",
                            CreatedAt = new DateTime(2025, 12, 6, 22, 45, 3, 323, DateTimeKind.Local).AddTicks(1736),
                            DefaultCanvasColor = "#FFFFFFFF",
                            DefaultCanvasHeight = 600.0,
                            DefaultCanvasWidth = 800.0,
                            DefaultStrokeColor = "#FF000000",
                            DefaultStrokeSize = 2.0,
                            DefaultStrokeStyle = 0,
                            LastAccessed = new DateTime(2025, 12, 6, 22, 45, 3, 323, DateTimeKind.Local).AddTicks(1761),
                            ThemePreference = "Dark",
                            UserName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
